import { useEffect, useRef, useState } from 'react';
import { invoke, isTauri } from '@tauri-apps/api/core';
import { Activity, ArrowDown, ArrowUp, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, FileText, FolderOpen, History, Info, Network, Play, Radio, RefreshCw, Search, ShieldCheck, Square, Target, TriangleAlert, Wifi, X } from 'lucide-react';
import type { Adapter, Catalog, Environment, Event, GameContext, HistoryItem, Probe, ProcessInfo, Report, SessionView, Tick } from './types';
import { FollowingPanel, ReportReadout, ConnectionHistory, eventTime } from './Tracking';

const empty: SessionView = { id: null, status: 'idle', elapsed: 0, durationSeconds: 600, logDir: null, tick: null, probes: [], events: [], hops: [], report: null, error: null };
const statusNames: Record<string, string> = { idle: '准备就绪', running: '正在测试', stopping: '正在结束并保存', stopped: '已提前结束', completed: '测试完成', error: '测试中断', incomplete: '未完成' };
const probeNames: Record<string, string> = { ok: '已回应', timeout: '超时', refused: '拒绝连接', error: '测量错误', unsupported: '不支持', hop: '路径节点', sampling_gap: '采样缺口' };
const clock = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`;
const ms = (value: number | null | undefined) => value == null ? '—' : value.toFixed(1);
const localTime = (date: string) => new Date(date).toLocaleTimeString('zh-CN', { hour12: false });
function bytes(value: number | null | undefined, rate = false): string { if (value == null) return '—'; const units = ['B', 'KB', 'MB', 'GB']; let i = 0; while (value >= 1024 && i < 3) { value /= 1024; i++; } return `${value.toFixed(i ? 1 : 0)} ${units[i]}${rate ? '/s' : ''}`; }
const palette: Record<string, string> = { gateway: '#147d86', reference: '#7b6bb0', server: '#2458a6', game: '#b64b32', relay: '#8b5a17' };

function Trend({ probes, elapsed }: { probes: Probe[]; elapsed: number }) {
  const [hover, setHover] = useState<Probe | null>(null);
  const recent = probes.filter(p => p.method === 'ICMP' && p.elapsed >= Math.max(0, elapsed - 180));
  const max = Math.max(100, ...recent.map(p => p.ms ?? 0)) * 1.1;
  const left = Math.max(0, elapsed - 180), span = Math.max(30, Math.min(180, elapsed));
  const x = (t: number) => 54 + (t - left) / span * 862;
  const y = (n: number) => 204 - n / max * 176;
  const groups = [...new Set(recent.map(p => p.target))].map(target => recent.filter(p => p.target === target));
  return <div className="trend-wrap">
    <svg className="trend" viewBox="0 0 940 245" role="img" aria-label="最近三分钟 ICMP 往返延迟曲线，超时显示在底部；具体数据见下方探测明细">
      {[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="54" x2="920" y1={y(max * i / 4)} y2={y(max * i / 4)} className="grid-line" /><text x="42" y={y(max * i / 4) + 4} textAnchor="end">{Math.round(max * i / 4)}</text></g>)}
      {[0, 1, 2, 3].map(i => <text key={i} x={54 + i * 862 / 3} y="235" textAnchor={i === 0 ? 'start' : i === 3 ? 'end' : 'middle'}>{clock(left + span * i / 3)}</text>)}
      <text x="17" y="14">ms</text>
      {groups.map(ps => { let pen = false; const d = ps.map((p, i) => { if (p.status !== 'ok' || p.ms == null) { pen = false; return ''; } const gap = i > 0 && p.elapsed - ps[i - 1].elapsed > 5; const command = pen && !gap ? 'L' : 'M'; pen = true; return `${command}${x(p.elapsed)},${y(p.ms)}`; }).join(' '); return <g key={ps[0].target}><path d={d} fill="none" stroke={palette[ps[0].role]} strokeWidth="2.2" strokeDasharray={ps[0].role === 'reference' ? '5 3' : undefined} />{ps.map((p, i) => <circle key={i} cx={x(p.elapsed)} cy={p.ms == null ? 213 : y(p.ms)} r={p.status === 'timeout' ? 3.5 : 3} className={p.status === 'timeout' ? 'timeout-dot' : 'sample-dot'} fill={p.status === 'ok' ? palette[p.role] : '#b64b32'} onMouseEnter={() => setHover(p)} onMouseLeave={() => setHover(null)}><title>{`${p.label} ${clock(p.elapsed)} ${p.status === 'ok' ? `${ms(p.ms)} ms` : probeNames[p.status]}`}</title></circle>)}</g>; })}
    </svg>
    {recent.length === 0 && <div className="chart-empty"><Activity size={28} aria-hidden="true" /><strong>等待第一组网络样本</strong><span>开始测试后，在这里对照网关、公网与游戏目标的延迟。</span></div>}
    {hover && <div className="chart-tooltip">{hover.label}　{clock(hover.elapsed)}　<strong>{hover.status === 'ok' ? `${ms(hover.ms)} ms` : probeNames[hover.status]}</strong></div>}
  </div>;
}
function Timeline({ events }: { events: Event[] }) {
  return <div className="timeline">{events.length === 0 ? <div className="quiet-empty"><Clock3 size={25} aria-hidden="true" /><p>测试开始后，连接变化和卡顿标记会出现在这里。</p></div> : [...events].reverse().map((e, i) => <div className={`timeline-item ${e.level}`} key={`${e.at}-${i}`}><time title={e.at}>{clock(e.elapsed)}</time><i aria-hidden="true" /><div><strong>{e.kind === 'marker' ? '玩家卡顿标记' : e.kind === 'endpoint_change' ? '地址变化' : e.kind === 'target_transition' ? '重点连接调整' : e.kind === 'relay' ? '中转进程' : e.kind === 'game_connections' ? '游戏连接变化' : e.kind === 'gap' ? '采样缺口' : '观测记录'}</strong><p>{e.message}</p></div></div>)}</div>;
}
function EnvironmentPanel({ env }: { env: Environment | null }) {
  if (!env) return <p className="muted">尚未读取本机环境。</p>;
  return <><div className="adapter-list">{env.adapters.filter(a => a.status === '已连接' || a.index === env.selectedInterface).map(a => <div className="adapter" key={a.index}><div className="row"><Network size={18} aria-hidden="true" /><strong>{a.name}</strong>{a.index === env.selectedInterface && <span className="tag">当前出接口</span>}</div><p>{a.description} · {a.kind}</p><dl><dt>本机地址</dt><dd>{a.addresses.join(' / ') || '不可用'}</dd><dt>网关</dt><dd>{a.gateways.join(' / ') || '未提供'}</dd><dt>DNS</dt><dd>{a.dns.join(' / ') || '未提供'}</dd><dt>网卡错误 / 丢弃</dt><dd>{a.inErrors + a.outErrors} / {a.inDiscards + a.outDiscards}（系统累计）</dd></dl></div>)}</div>{env.wifi.map(s => <p className="note" key={s}><Wifi size={16} aria-hidden="true" />{s}</p>)}{env.notes.map(s => <p className="note" key={s}><Info size={16} aria-hidden="true" />{s}</p>)}</>;
}
function ProcessTable({ tick }: { tick: Tick | null }) {
  const [filter, setFilter] = useState(''); const [expanded, setExpanded] = useState<string | null>(null); const [sort, setSort] = useState('traffic');
  const list = (tick?.processes ?? []).filter(p => `${p.name} ${p.pid} ${p.path ?? ''}`.toLowerCase().includes(filter.toLowerCase()));
  const amount = (pid: number) => { const t = tick?.traffic.find(t => t.pid === pid); return (t?.receiveBps ?? 0) + (t?.sendBps ?? 0); };
  list.sort((a, b) => sort === 'connections' ? (tick?.connections.filter(c => c.pid === b.pid).length ?? 0) - (tick?.connections.filter(c => c.pid === a.pid).length ?? 0) : amount(b.pid) - amount(a.pid));
  return <section className="panel"><div className="panel-heading"><div><h2>本机联网程序</h2><p>展开查看 EXE 路径和连接。流量来自系统网络事件。</p></div><span className="count">{list.length} 个进程</span></div>
    <div className="table-tools"><label className="search-field"><Search size={17} aria-hidden="true" /><input aria-label="搜索联网进程" placeholder="搜索程序、PID 或路径" value={filter} onChange={e => setFilter(e.target.value)} /></label><label className="sort-field">排序<select value={sort} onChange={e => setSort(e.target.value)}><option value="traffic">当前流量</option><option value="connections">连接数量</option></select></label></div>
    <div className={`notice ${tick?.trafficStatus.available ? 'subtle' : ''}`}><Info size={17} aria-hidden="true" /><span>{tick?.trafficStatus.message ?? '开始测试后采集本机连接；每进程流量可能需要管理员权限。'}</span></div>
    <div className="process-list"><div className="process-row table-header"><span>程序 / PID</span><span>上传</span><span>下载</span><span>观测累计</span><span>连接</span></div>{list.slice(0, 200).map(p => { const identity = `${p.pid}:${p.started}`; const t = tick?.traffic.find(t => t.pid === p.pid); const connections = tick?.connections.filter(c => c.pid === p.pid) ?? []; const isOpen = expanded === identity; return <div className="process-entry" key={identity}><button className={`process-row ${isOpen ? 'selected' : ''}`} aria-expanded={isOpen} onClick={() => setExpanded(isOpen ? null : identity)}><span className="process-name">{isOpen ? <ChevronDown size={16} /> : <ChevronRight size={16} />}<span><strong>{p.name}</strong><small>PID {p.pid}{p.pid === tick?.gamePid ? ' · 监控的游戏' : p.name.includes('network-diagnostics') ? ' · 本工具' : ''}</small></span></span><span>{bytes(t?.sendBps, true)}</span><span>{bytes(t?.receiveBps, true)}</span><span>{t ? bytes(t.received + t.sent) : '—'}</span><span>{connections.length}</span></button>{isOpen && <div className="process-details"><label>EXE 完整路径<input readOnly aria-label={`${p.name} 完整路径`} value={p.path ?? '路径不可读取，可能需要更高权限'} onFocus={e => e.target.select()} /></label><p>启动标识：{p.started ?? '不可读，未归属流量'}　内存：{bytes(p.memoryBytes)}{p.pid === tick?.gamePid && `　CPU：${ms(p.cpuPercent)}%（整机归一化）`}</p><div className="scroll-table"><table><thead><tr><th>协议</th><th>本地端点</th><th>远端</th><th>状态</th></tr></thead><tbody>{connections.slice(0, 100).map((c, i) => <tr key={i}><td>{c.protocol}</td><td className="mono">{c.local}</td><td className="mono">{c.remote ?? 'UDP：见自动跟随连接记录'}</td><td>{c.state}</td></tr>)}</tbody></table></div>{connections.length > 100 && <p>界面显示前 100 条连接，完整快照保存在日志中。</p>}</div>}</div>; })}</div>
    {list.length === 0 && <div className="quiet-empty"><Network size={32} aria-hidden="true" /><p>{tick ? '没有匹配的进程。' : '开始测试，查看这台电脑上的联网程序。'}</p></div>}{list.length > 200 && <p className="note">界面显示前 200 个进程，请搜索具体程序。</p>}
  </section>;
}
function ReportView({ report, open }: { report: Report; open: (id: string) => void }) {
  return <div className="report-view"><section className="report-intro"><div><div className="row"><FileText size={23} aria-hidden="true" /><span className="tag">{statusNames[report.status]}</span></div><h2>{report.server.name} · 网络诊断报告</h2><p>{new Date(report.startedAt).toLocaleString('zh-CN')}　持续 {clock(report.durationSeconds)}</p></div><button className="button" onClick={() => open(report.id)}><FolderOpen size={17} aria-hidden="true" />打开报告与日志</button></section>
    <ReportReadout report={report} /><ConnectionHistory report={report} />
    <div className="findings">{report.findings.map((f, i) => <article className={`finding ${f.level}`} key={i}><div className="finding-icon">{f.level === 'warning' ? <TriangleAlert size={23} aria-hidden="true" /> : <Info size={23} aria-hidden="true" />}</div><div><div className="row"><span className="tag">{eventTime(report.startedAt, f.start)} – {eventTime(report.startedAt, f.end)}（第 {clock(f.start)} 起）</span><span className="muted">判断把握：{f.confidence}</span></div><h3>{f.title}</h3><ul>{f.evidence.map((e, j) => <li key={j}>{e}</li>)}</ul><p className="recommendation">{f.suggestion}</p></div></article>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>目标统计</h2><p>延迟单位 ms；“95% 上限”只统计成功回应。超时不是游戏丢包。</p></div></div><div className="scroll-table"><table><thead><tr><th>目标 / 方式</th><th>成功 / 发送</th><th>超时</th><th>其他错误</th><th>通常延迟</th><th>95% 上限</th><th>最大值</th><th>平均相邻差</th></tr></thead><tbody>{report.stats.map(s => <tr key={`${s.target}:${s.method}`}><td><strong>{s.label}</strong><small>{s.target} · {s.method}{!s.assessable ? ' · 样本不足' : ''}</small></td><td>{s.success} / {s.sent}</td><td>{s.timeouts}</td><td>{s.errors}</td><td>{ms(s.p50)}</td><td>{ms(s.p95)}</td><td>{ms(s.max)}</td><td>{ms(s.jitter)}</td></tr>)}</tbody></table></div></section>
    <section className="panel padded"><h2>本次观测范围</h2><p>{report.trafficStatus.message}</p><ul className="limits">{report.limitations.map(s => <li key={s}>{s}</li>)}</ul><p className="mono path">{report.logDir}</p></section><section className="panel padded"><h2>完整事件时间线</h2><Timeline events={report.events} /></section>
  </div>;
}

export default function App() {
  const desktop = isTauri();
  const [page, setPage] = useState('monitor'); const [catalog, setCatalog] = useState<Catalog | null>(null); const [processes, setProcesses] = useState<ProcessInfo[]>([]); const [environment, setEnvironment] = useState<Environment | null>(null);
  const [serverId, setServerId] = useState(''); const [serverSearch, setServerSearch] = useState(''); const [gameKey, setGameKey] = useState(''); const [minutes, setMinutes] = useState(10); const [durationChoice, setDurationChoice] = useState('10');
  const [session, setSession] = useState<SessionView>(empty); const [history, setHistory] = useState<HistoryItem[]>([]); const [report, setReport] = useState<Report | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [environmentOpen, setEnvironmentOpen] = useState(false);
  const lastStatus = useRef('idle');
  const [gameContext, setGameContext] = useState<GameContext | null>(null);
  const running = ['running', 'stopping'].includes(session.status); const selected = catalog?.servers.find(s => s.id === serverId); const chosenGame = processes.find(p => `${p.pid}:${p.started}` === gameKey);
  const currentEnv = session.tick?.environment ?? environment; const adapter: Adapter | undefined = currentEnv?.adapters.find(a => a.index === currentEnv.selectedInterface);
  const game = session.tick?.processes.find(p => p.pid === session.tick?.gamePid) ?? chosenGame;
  async function perform<T>(name: string, action: () => Promise<T>): Promise<T | undefined> { setBusy(name); setError(null); try { return await action(); } catch (e) { setError(String(e)); } finally { setBusy(''); } }
  const refreshProcesses = () => perform('processes', async () => { const ps = await invoke<ProcessInfo[]>('get_processes'); setProcesses(ps); });
  const refreshHistory = () => perform('history', async () => { setHistory(await invoke<HistoryItem[]>('get_history')); });
  const openLogs = (id: string) => { void perform('logs', () => invoke('open_logs', { id })); };
  useEffect(() => {
    let cancelled = false; if (!desktop) return;
    const init = async () => { const results = await Promise.allSettled([invoke<Catalog>('get_catalog', { refresh: false }), invoke<ProcessInfo[]>('get_processes'), invoke<Environment>('get_environment')]); if (cancelled) return;
      const [c, p, e] = results; if (c.status === 'fulfilled') { setCatalog(c.value); setServerId(c.value.servers.find(s => s.name === '绝代天骄')?.id ?? c.value.servers[0]?.id ?? ''); } if (p.status === 'fulfilled') { setProcesses(p.value); const g = p.value.find(p => p.isGame && p.path && p.started); if (g) setGameKey(`${g.pid}:${g.started}`); } if (e.status === 'fulfilled') setEnvironment(e.value);
      const failures = results.filter((r): r is PromiseRejectedResult => r.status === 'rejected'); if (failures.length) setError(failures.map(r => String(r.reason)).join('；'));
    }; void init(); let timer: ReturnType<typeof setTimeout>;
    const poll = async () => { try { const view = await invoke<SessionView>('get_session'); if (cancelled) return; setSession(view); if (view.report && lastStatus.current !== view.status) { setReport(view.report); setPage('report'); } lastStatus.current = view.status; } catch (e) { if (!cancelled) setError(`读取测试状态失败：${String(e)}`); } if (!cancelled) timer = setTimeout(poll, 1000); }; void poll();
    return () => { cancelled = true; clearTimeout(timer); };
  }, [desktop]);
  useEffect(() => {
    let cancelled = false;
    if (!desktop || running || !chosenGame?.started) { if (!running) setGameContext(null); return; }
    void invoke<GameContext>('inspect_game', { pid: chosenGame.pid, started: chosenGame.started }).then(context => {
      if (cancelled) return;
      setGameContext(context);
      if (context.matches.length === 1) { setServerId(context.matches[0].id); setNotice(`已按游戏连接匹配目录入口：${context.matches[0].name}；跨服地址仍会自动跟随。`); }
    }).catch(e => { if (!cancelled) setError(`识别游戏连接失败：${String(e)}`); });
    return () => { cancelled = true; };
  }, [desktop, gameKey, running]);
  async function start() { if (!selected) return; const result = await perform('start', async () => { await invoke('start_test', { config: { server: selected, durationSeconds: Math.round(minutes * 60), gamePid: chosenGame?.pid ?? null, gameStarted: chosenGame?.started ?? null } }); setSession(await invoke<SessionView>('get_session')); setReport(null); setPage('monitor'); }); return result; }
  const latest: Probe[] = [...new Map(session.probes.map(p => [`${p.target}:${p.method}`, p])).values()];
  const focusIp = session.tick?.tracking?.primaryIp;
  const lastServer = [...session.probes].reverse().find(p => p.method === 'ICMP' && (focusIp ? p.target === focusIp : p.role === 'server'));
  const routeHops = session.hops.filter(h => h.target === (focusIp && session.tick?.tracking.probeIps.includes(focusIp) ? focusIp : selected?.endpoints[0]?.ip));
  const gameActive = Boolean(session.tick?.gamePid); const title = { monitor: '实时诊断', processes: '联网程序', history: '测试记录', report: '诊断报告', guide: '使用说明' }[page];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Activity size={29} strokeWidth={2} aria-hidden="true" /></div><div><strong>剑网三</strong><span>网络诊断工具</span></div></div><nav aria-label="主导航">{[{ key: 'monitor', label: '实时诊断', icon: Activity }, { key: 'processes', label: '联网程序', icon: Network }, { key: 'report', label: '诊断报告', icon: FileText }, { key: 'history', label: '测试记录', icon: History }].map(n => <button key={n.key} className={page === n.key ? 'active' : ''} aria-current={page === n.key ? 'page' : undefined} onClick={() => { setPage(n.key); if (n.key === 'history' && desktop) void refreshHistory(); }}><n.icon size={19} aria-hidden="true" />{n.label}{n.key === 'report' && report && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="local-badge"><ShieldCheck size={19} aria-hidden="true" /><div>日志保存在本机<small>无需账号，不上传诊断数据</small></div></div><button className={page === 'guide' ? 'active' : ''} onClick={() => setPage('guide')}><CircleHelp size={18} aria-hidden="true" />使用说明</button><p>Windows 桌面版 <span>0.2.0</span></p></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">网络观测台<ChevronRight size={14} aria-hidden="true" /><strong>{title}</strong></div><div className={`session-status ${session.status}`}><span className="status-dot" />{statusNames[session.status] ?? session.status}{running && <span className="mono">{clock(session.elapsed)} / {clock(session.durationSeconds)}</span>}</div></header>
      <main><div className="page-title"><div><h1>{title}</h1><p>{page === 'monitor' ? '记录每一次波动，让卡顿有迹可循。' : page === 'processes' ? '把游戏卡顿与后台程序的网络活动对齐。' : page === 'history' ? '查阅本机保存的测试结果与原始记录。' : page === 'report' ? '根据同一时段的多组观测，缩小问题范围。' : '了解测量范围，让诊断结论更可靠。'}</p></div>{session.id && <button className="button quiet" onClick={() => openLogs(session.id!)}><FolderOpen size={17} aria-hidden="true" />日志目录</button>}</div>
      {!desktop && <div className="notice"><Info size={19} aria-hidden="true" /><span>当前为浏览器界面预览。请运行桌面 EXE，以读取本机进程并开始真实网络测试。</span></div>}
      {(error || session.error) && <div className="notice danger" role="alert"><TriangleAlert size={18} aria-hidden="true" /><span>{error ?? session.error}</span>{error && <button className="icon-button" aria-label="关闭错误提示" onClick={() => setError(null)}><X size={17} /></button>}</div>}
      {notice && <div className="notice subtle" role="status"><Check size={17} aria-hidden="true" /><span>{notice}</span><button className="icon-button" aria-label="关闭提示" onClick={() => setNotice(null)}><X size={17} /></button></div>}
      {page === 'monitor' && <>
        <section className="panel setup-panel"><div className="setup-top"><div className="row"><Target size={19} aria-hidden="true" /><h2>测试目标</h2></div><button className="text-button" disabled={!desktop || running || Boolean(busy)} onClick={() => void perform('catalog', async () => { const c = await invoke<Catalog>('get_catalog', { refresh: true }); setCatalog(c); if (!c.servers.some(s => s.id === serverId)) setServerId(c.servers[0]?.id ?? ''); })}><RefreshCw size={14} className={busy === 'catalog' ? 'spin' : ''} aria-hidden="true" />更新区服</button></div>
          <div className="setup-grid"><div className="server-field"><label htmlFor="server-search">所属区服 / 入口参照</label><div className="server-controls"><input id="server-search" aria-label="搜索区服或合服前名称" placeholder="搜索现名或旧名" value={serverSearch} disabled={running} onChange={e => setServerSearch(e.target.value)} /><select aria-label="选择服务器" value={serverId} disabled={running || !catalog} onChange={e => setServerId(e.target.value)}>{!catalog && <option value="">等待目录</option>}{[...new Set(catalog?.servers.map(s => s.area))].map(area => <optgroup label={area} key={area}>{catalog?.servers.filter(s => s.area === area && (s.id === serverId || `${s.name} ${s.aliases.join(' ')}`.includes(serverSearch))).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</optgroup>)}</select></div></div>
            <div><label htmlFor="duration">测试时长</label><select id="duration" disabled={running} value={durationChoice} onChange={e => { setDurationChoice(e.target.value); if (e.target.value !== 'custom') setMinutes(Number(e.target.value)); }}><option value="5">5 分钟</option><option value="10">10 分钟</option><option value="30">30 分钟</option><option value="60">60 分钟</option><option value="custom">自定义时长</option></select>{durationChoice === 'custom' && <label className="custom-duration"><input type="number" aria-label="自定义分钟数" min="1" max="180" step="1" value={minutes} disabled={running} onChange={e => setMinutes(Number(e.target.value))} />分钟（1–180）</label>}</div>
            <div className="start-actions">{running ? <button className="button stop-button" disabled={session.status === 'stopping' || Boolean(busy)} onClick={() => void perform('stop', () => invoke('stop_test'))}><Square size={16} fill="currentColor" aria-hidden="true" />{session.status === 'stopping' ? '正在保存…' : '结束并分析'}</button> : <button className="button primary" disabled={!desktop || !selected || Boolean(busy) || !Number.isInteger(minutes) || minutes < 1 || minutes > 180} onClick={() => void start()}><Play size={18} fill="currentColor" aria-hidden="true" />{busy === 'start' ? '正在启动…' : '开始测试'}</button>}</div></div>
          <div className="game-selector"><label htmlFor="game-process">关联游戏进程<span>可选</span></label><select id="game-process" disabled={running || !desktop} value={gameKey} onChange={e => setGameKey(e.target.value)}><option value="">不关联进程，仅测试区服与网络</option>{processes.filter(p => p.path && p.started).map(p => <option value={`${p.pid}:${p.started}`} key={`${p.pid}:${p.started}`}>{p.isGame ? '游戏候选 · ' : ''}{p.name}（PID {p.pid}）</option>)}</select><button className="icon-button" aria-label="刷新进程列表" title="刷新进程列表" disabled={running || !desktop || Boolean(busy)} onClick={() => void refreshProcesses()}><RefreshCw size={17} className={busy === 'processes' ? 'spin' : ''} /></button></div>
          {chosenGame?.path && <div className="selected-path"><span>EXE</span><input readOnly aria-label="所选游戏完整路径" value={chosenGame.path} onFocus={e => e.target.select()} /></div>}
          <div className="setup-foot"><span>{selected ? `${selected.endpoints.length} 个接入地址 · ${selected.aliases.length} 个现名与旧名` : '目录按合服后的区服名称归并'}</span><span>{catalog ? `${catalog.source} · ${catalog.fetchedAt.slice(0, 10)}` : '离线目录可用'}</span></div>{catalog?.warning && <p className="inline-warning">{catalog.warning}</p>}
        </section>
        <FollowingPanel tracking={session.tick?.tracking} context={gameContext} />
        <div className="metrics-strip"><div><span>{focusIp ? '重点地址探测延迟' : '区服入口参照延迟'} <small>ICMP</small></span><strong>{ms(lastServer?.status === 'ok' ? lastServer.ms : null)}<small>ms</small></strong><p>{lastServer ? probeNames[lastServer.status] : '等待测量'}</p></div><div><span>当前出接口上传</span><strong>{bytes(adapter?.sendBps, true)}</strong><p><ArrowUp size={13} aria-hidden="true" />{adapter?.name ?? '尚未识别'}</p></div><div><span>当前出接口下载</span><strong>{bytes(adapter?.receiveBps, true)}</strong><p><ArrowDown size={13} aria-hidden="true" />各网卡分别统计</p></div><div><span>游戏进程</span><strong className="game-metric">{gameActive ? '正在观测' : running && chosenGame ? '等待重新关联' : chosenGame ? '已选择' : '未关联'}</strong><p>{game ? `${game.name} · PID ${game.pid}` : '关联后跟踪实际连接'}</p></div></div>
        <section className="panel chart-panel"><div className="panel-heading"><div><h2>网络延迟时间线</h2><p>最近 3 分钟 · ICMP 约每 2 秒采样</p></div><button className="button marker-button" disabled={session.status !== 'running' || Boolean(busy)} onClick={() => void perform('mark', async () => { await invoke('mark_event'); setNotice('已记录卡顿标记，将与前后测量数据一起分析。'); })}><Radio size={17} aria-hidden="true" />刚刚卡了</button></div><div className="legend">{[['gateway', '本地网关'], ['reference', '公网参照'], ['server', '区服接入'], ['game', '游戏可见远端'], ['relay', '加速/代理候选']].map(([key, text]) => <span key={key}><i style={{ background: palette[key] }} />{text}</span>)}<span><i className="timeout-key" />超时 / 错误</span></div><Trend probes={session.probes} elapsed={session.elapsed} /><div className="chart-foot"><span><Info size={14} aria-hidden="true" />探测延迟用于对照，不等同游戏内延迟。</span><span>{session.tick ? `最后采样 ${localTime(session.tick.at)}` : '尚未采样'}</span></div></section>
        <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>探测明细</h2><p>ICMP 与 TCP 建连分别记录</p></div><span className="count">{latest.length} 组</span></div><div className="probe-list">{latest.length === 0 ? <div className="quiet-empty"><Target size={28} aria-hidden="true" /><p>选择区服并开始测试，自动添加网关与公网参照。</p></div> : latest.map(p => <div className="probe-row" key={`${p.target}:${p.method}`}><span className="target-symbol" style={{ color: palette[p.role] }}><Target size={19} aria-hidden="true" /></span><div><strong>{p.label}</strong><small>{p.target} · {p.method}</small></div><span className={`probe-value ${p.status}`} title={p.detail ?? undefined}>{p.status === 'ok' ? `${ms(p.ms)} ms` : probeNames[p.status]}</span></div>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>事件时间线</h2><p>连接变化、能力状态与体感标记</p></div></div><Timeline events={session.events} /></section></div>
        <section className="panel"><button className="disclosure" onClick={() => setEnvironmentOpen(!environmentOpen)} aria-expanded={environmentOpen}><span><Network size={18} aria-hidden="true" />本机网络环境与路径</span>{environmentOpen ? <ChevronDown size={18} /> : <ChevronRight size={18} />}</button>{environmentOpen && <div className="padded"><EnvironmentPanel env={currentEnv} />{session.hops.length > 0 && <div className="route"><h3>到当前重点地址的路径探测</h3><p className="muted">未回应只表示此跳未返回探测结果，不能据此认定游戏丢包。</p><div>{routeHops.map(h => <span className="hop" key={`${h.target}:${h.ttl}`}><b>{h.ttl}</b>{h.address ?? '未回应'}<small>{h.ms == null ? '—' : `${ms(h.ms)} ms`}</small></span>)}</div></div>}</div>}</section>
      </>}
      {page === 'processes' && <ProcessTable tick={session.tick} />}
      {page === 'report' && (report ? <ReportView report={report} open={openLogs} /> : <section className="panel large-empty"><FileText size={42} aria-hidden="true" /><h2>测试结束后，在这里查看分析</h2><p>报告会包含异常时间段、相关证据、可能原因和下一步建议。</p><button className="button primary" onClick={() => setPage('monitor')}>前往实时诊断</button></section>)}
      {page === 'history' && <section className="panel"><div className="panel-heading"><div><h2>本机测试记录</h2><p>最近 200 次测试。未完成的记录保留原始日志。</p></div><button className="button" disabled={!desktop || Boolean(busy)} onClick={() => void refreshHistory()}><RefreshCw size={16} aria-hidden="true" />刷新</button></div>{history.length === 0 ? <div className="large-empty"><History size={36} aria-hidden="true" /><h3>还没有测试记录</h3><p>完成一次测试后，报告将自动保存到这里。</p></div> : history.map(h => <div className="history-row" key={h.id}><div><strong>{h.serverName}</strong><small>{new Date(h.startedAt).toLocaleString('zh-CN')}</small></div><span>{clock(h.durationSeconds)}</span><span className="tag">{statusNames[h.status]}</span><button className="button" disabled={h.status === 'incomplete' || Boolean(busy)} onClick={() => void perform('report', async () => { setReport(await invoke<Report>('get_report', { id: h.id })); setPage('report'); })}>查看报告</button><button className="icon-button" aria-label={`打开 ${h.serverName} 日志`} onClick={() => openLogs(h.id)}><FolderOpen size={18} /></button></div>)}</section>}
      {page === 'guide' && <div className="guide"><section className="panel padded"><h2>先开始测试，再照常玩游戏</h2><ol><li>选择合服后的区服，也可以通过旧名称搜索。</li><li>游戏已启动时，选择其进程并核对 EXE 路径。多开客户端时请确认 PID。</li><li>默认测试 10 分钟；偶发卡顿建议选择 30 分钟或更长。</li><li>出现卡顿或掉线时点击“刚刚卡了”。结束后查看报告中的证据与验证建议。</li></ol></section><section className="panel padded"><h2>怎样读懂数据</h2><dl><dt>网关、公网与游戏目标</dt><dd>同时观测不同目标，帮助缩小异常范围。公网参照正常不代表所有外网线路正常。</dd><dt>超时与丢包</dt><dd>部分设备限制 ICMP。工具记录的是探测超时，不能把它直接当作游戏丢包率。</dd><dt>后台程序流量</dt><dd>每进程流量需要可用的 Windows 网络事件采集。不可用时可尝试以管理员身份运行；不支持的数据显示“—”。每个网卡独立统计，加速器和虚拟网卡可能重复观测流量。</dd><dt>进程与路径</dt><dd>进程以 PID 和创建时间关联。原进程退出后，只有同一 EXE 路径存在唯一候选时才自动重新关联。</dd><dt>加速器与 IPv6</dt><dd>工具按本地端口对应关系反查中转进程，并跟踪游戏和中转进程的 TCP / UDP 上游候选；不依赖固定加速器名称。虚拟网卡、驱动转发或隧道后的最终游戏服可能不可见。主动 ICMP 支持 IPv4，探测不一定经过游戏隧道。</dd><dt>日志与报告</dt><dd>日志包含连接地址、程序路径、采样及标记，不保存网络正文，也不会自动上传。测试结束后目录内包含 report.html、report.json 与 samples.jsonl。未完成日志暂不自动重新分析。</dd></dl></section></div>}
      <footer><span>探测结果提供排查线索，结论以实际观测证据为依据。</span><span>本地记录 · 无云端分析</span></footer>
      </main></div></div>;
}
